menu:
    主页: /
    文章: /archives
    留言板: /msgboard
    GitHub: https://github.com/coderneko
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: coderneko

# Analytics
# google-analytics:
ga: UA-93917158-1

# Copyright Infomation
startyear: 2017
